### PR TITLE
Updated outdated.md

### PR DESCRIPTION
**Pull request by mcenderdragon**
@gloomybanana could you please check if the Chinese tr ansöation is still up-to-date with the english one ?

@NeoFight92  could you do the same for the french translation ?

@a22brad22 it would be nice if you could check if the pt_br translation is alright.

### CODE REVIEW

**Comment by mcenderdragon** [comment]
Last Update at So, 17. Dez 2017 13:47:12


Parent Dir de_de , Sub Dir zh_cn

| File | Time diff | Commit |
| --- | --- | --- |
| zh_cn/calculation.json | 17 min | Wugi:UTF-8 |
| zh_cn/menelaus.json | 112 days | Wugi:Update to current state |
| zh_cn/production.recycler.analyzer.json | 17 min | Wugi:UTF-8 |
| zh_cn/production.recycler.json | 17 min | Wugi:UTF-8 |
| zh_cn/production.recycler.lasercutter.json | 17 min | Wugi:UTF-8 |
| zh_cn/production.recycler.shredder.json | 17 min | Wugi:UTF-8 |
| zh_cn/space.turret.killer.json | 112 days | Wugi:Update to current state |
| zh_cn/techtabel.json | 112 days | Wugi:Update to current state |
| zh_cn/upgradeT3.json | 17 min | Wugi:UTF-8 |


Parent Dir de_de , Sub Dir en_us

| File | Time diff | Commit |
| --- | --- | --- |


Parent Dir de_de , Sub Dir fr_fr

| File | Time diff | Commit |
| --- | --- | --- |
| fr_fr/menelaus.json | 203 days | Wugi:Update to current state |
| fr_fr/production.nind.special.json | 203 days | Wugi:Update to current state |
| fr_fr/space.turret.killer.json | 203 days | Wugi:Update to current state |
| fr_fr/techtabel.json | 203 days | Wugi:Update to current state |
| fr_fr/upgradeT3.json | 93 days | Wugi:UTF-8 |


Parent Dir de_de , Sub Dir pt_br

| File | Time diff | Commit |
| --- | --- | --- |
| pt_br/menelaus.json | 203 days | Wugi:Update to current state |
| pt_br/space.turret.killer.json | 203 days | Wugi:Update to current state |
| pt_br/techtabel.json | 203 days | Wugi:Update to current state |
| pt_br/upgradeT3.json | 70 days | Wugi:UTF-8 |

**Comment by a22brad22** [comment]
I'm pretty sure all the English and Portuguese files are now entirely up-to-date. Let me know if I missed something.

**Comment by gloomybanana** [comment]
I'm sure all the  Chinese translation is still up-to-date with the English one .

**Comment by dal62599** [comment]
I donot want a subscription nor did i authorize anyone todo so. So please cancel everything with github.

Sent from Yahoo Mail on Android 
 
  On Sun, Dec 17, 2017 at 7:54 AM, mcenderdragon<notifications@github.com> wrote:   
@gloomybanana could you please check if the Chinese tr ansöation is still up-to-date with the english one ?

@NeoFight92 could you do the same for the french translation ?

@a22brad22 it would be nice if you could check if the pt_br translation is alright.

You can view, comment on, or merge this pull request online at:

  https://github.com/Wugand/FuturePack-Language/pull/145

Commit Summary
   
   - updated outdated.md

File Changes
   
   -  M outdated.md (18) 

Patch Links:
   
   - https://github.com/Wugand/FuturePack-Language/pull/145.patch
   - https://github.com/Wugand/FuturePack-Language/pull/145.diff

**Pull request merged**
