### PR TITLE
Iceink001 add ja_jp

### PR DESCRIPTION
**Pull request by iceink001**
Futurepack-1.12.2-26.3.48
en_us→ja_jp
こんにちは。
Have I uploaded it?

### CODE REVIEW

**Comment by mcenderdragon** [comment]
Ohh my god thanks :D This is amazing. I think you have made a tiny mistake: ther is a file called ja_jp_01/hs.ther*o*modynamik.json and it is still in english, but you alredy have thermodynamik so you can  just delete the wrong spellen one.

**Comment by iceink001** [comment]
I thought that it might not be necessary.I made a correction.
This time, my two friends have elaborated the text.
It is still uncertain about how to use github.The number of folders has increased.

**Comment by mcenderdragon** [comment]
Is the translation completed, can we merge this?

**Comment by iceink001** [comment]
yes!よろしくお願いします。

**Comment by Wugand** [comment]
Ok, thank you very much.
It's merged and will be in the next release.

**Pull request merged**
